import { 
  LayoutDashboard, 
  Users, 
  Filter, 
  FileText, 
  Building2, 
  HelpCircle, 
  LogOut,
  Bell,
  Settings,
  TrendingUp,
  ExternalLink,
  Cake,
  MoreVertical,
  Search,
  Plus,
  ChevronLeft,
  ChevronRight,
  ChevronUp,
  UploadCloud,
  CheckCircle2,
  Phone,
  Mail,
  X,
  Check,
  Info,
  Menu,
  ChevronDown,
  MapPin,
  Briefcase,
  Heart,
  History,
  CreditCard,
  Target,
  MessageSquare,
  Calendar,
  Clock,
  Trash2,
  Edit2,
  AlertCircle,
  UserPlus,
  Shield,
  Camera,
  Lock,
  Eye,
  EyeOff,
  Image,
  Paperclip,
  FileSearch,
  Download,
  Trophy,
  Gem,
  Loader2,
  Mic,
  Play,
  File,
  Save,
  Rocket
} from "lucide-react";

export const Icons = {
  Dashboard: LayoutDashboard,
  Leads: Users,
  Funnel: Filter,
  Contracts: FileText,
  FileText: FileText,
  Carriers: Building2,
  Building2: Building2,
  Filter: Filter,
  Support: HelpCircle,
  Logout: LogOut,
  Notifications: Bell,
  Bell: Bell,
  Settings: Settings,
  TrendingUp: TrendingUp,
  Cake: Cake,
  More: MoreVertical,
  Search: Search,
  Plus: Plus,
  ChevronLeft: ChevronLeft,
  ChevronRight: ChevronRight,
  ChevronUp: ChevronUp,
  Upload: UploadCloud,
  CheckCircle: CheckCircle2,
  Phone: Phone,
  Mail: Mail,
  X: X,
  Check: Check,
  Info: Info,
  Menu: Menu,
  ChevronDown: ChevronDown,
  MapPin: MapPin,
  Briefcase: Briefcase,
  Heart: Heart,
  History: History,
  CreditCard: CreditCard,
  Target: Target,
  MessageSquare: MessageSquare,
  Users: Users,
  Calendar: Calendar,
  Clock: Clock,
  Trash: Trash2,
  Edit: Edit2,
  AlertCircle: AlertCircle,
  UserPlus: UserPlus,
  Shield: Shield,
  Camera: Camera,
  Lock: Lock,
  Eye: Eye,
  EyeOff: EyeOff,
  Image: Image,
  Paperclip: Paperclip,
  FileSearch: FileSearch,
  Download: Download,
  Trophy: Trophy,
  Gem: Gem,
  Loader2: Loader2,
  Mic: Mic,
  Play: Play,
  File: File,
  Save: Save,
  ExternalLink: ExternalLink,
  Rocket: Rocket
};
